---
title: "figaro-analysis-prep"
author: "Elisabeth Lindbo Hansen"
date: "`r date`"
output: html_document
params:
   inFullPath: ""
---

```{r setup, eval=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
```

```{r in, eval=TRUE, include=TRUE}

fullPath=params$inFullPath
#fullPath="/home/elhansen/FIGARO/figaro-results/201700000000"
fileNames=dir(fullPath, recursive=TRUE, all.files=FALSE, full.names=TRUE, pattern =".csv")
outFile=str_c(fullPath,".csv")
data=tibble(iX=numeric(),iY=numeric(),iZ=numeric(),Emin=numeric(),Emax=numeric(),sW=numeric(),sH=numeric(),sL=numeric(),value=numeric())
temp=data
for(i in 1:length(fileNames)){
  print(fileNames[i])
  temp=read_csv(fileNames[i],skip=3,col_names=c("iX","iY","iZ","value","value2","entry"),col_types="iiinni")
  regex=str_extract_all(fileNames[i], '[[:digit:]]+.[[:digit:]]+')
  temp$iZ=as.numeric(regex[[1]][5])
  temp=select(temp,iX,iY,iZ,value)
  temp=mutate(temp,sW=-as.numeric(regex[[1]][2]))
  temp=mutate(temp,sH=-as.numeric(regex[[1]][3]))
  temp=mutate(temp,sL=-as.numeric(regex[[1]][4]))
  temp=mutate(temp,Emin=as.numeric(regex[[1]][6]))
  temp=mutate(temp,Emax=as.numeric(regex[[1]][7]))
  data=bind_rows(data,temp)
  #data=summarise(group_by(data,iX,iY,iZ,sW,sH,sL),value=sum(value))
}
data$iX=data$iX-max(data$iX)/2
write_csv(data,outFile)

```
