---
title: "figaro-analysis-prep"
author: "Elisabeth Lindbo Hansen"
date: "`r date`"
output: html_document
params:
   inFullPath: ""
---

```{r setup, eval=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
```

```{r in, eval=TRUE, include=TRUE}

fullPath=params$inFullPath
#fullPath="/home/elhansen/FIGARO/figaro-results/201700000000"
fileNames=dir(fullPath, recursive=TRUE, all.files=FALSE, full.names=TRUE, pattern =".csv")
#outFile=str_c(fullPath,".csv")
data=tibble(iX=numeric(),iY=numeric(),iZ=numeric(),Emin=numeric(),Emax=numeric(),sW=numeric(),sH=numeric(),sL=numeric(),value=numeric())
temp=data
for(i in 1:length(fileNames)){
  print(fileNames[i])
  temp=read_csv(fileNames[i],skip=3,col_names=c("iX","iY","iZ","value","value2","entry"),col_types="iiinni")
  regex=str_extract_all(fileNames[i], '[[:digit:]]+.[[:digit:]]+')
  temp$iZ=as.numeric(regex[[1]][5])
  temp=select(temp,iX,iY,iZ,value)
  temp=mutate(temp,sW=-as.numeric(regex[[1]][2]))
  temp=mutate(temp,sH=-as.numeric(regex[[1]][3]))
  temp=mutate(temp,sL=-as.numeric(regex[[1]][4]))
  temp=mutate(temp,Emin=as.numeric(regex[[1]][6]))
  temp=mutate(temp,Emax=as.numeric(regex[[1]][7]))
  data=bind_rows(data,temp)
  #data=summarise(group_by(data,iX,iY,iZ,sW,sH,sL),value=sum(value))
}
data$iX=data$iX-max(data$iX)/2
#write_csv(data,outFile)

outGraphWidth902cm=str_c(fullPath,"Width902cm.ps")
outGraphHeight902cm=str_c(fullPath,"Height902cm.ps")
outGraphWidth1502cm=str_c(fullPath,"Width1502cm.ps")
outGraphHeight1502cm=str_c(fullPath,"Height1502cm.ps")
#data=read_csv(inFile,col_types = "iiinnnnnn")

ssdl<-read_csv("ssdl_2013.csv")
ssdl$w<-as.double(ssdl$w)
ssdl$h<-as.double(ssdl$h)
ssdl$h=ssdl$h+78
ssdl$l<-as.double(ssdl$l)
ssdl$l=ssdl$l+2
ssdlRef=139.4
ssdlRefUnc=4.5

#currentSource2003=summarise(group_by(filter(data,sH>=(-73.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
#currentSource2003$value=currentSource2003$value*8

#currentSource2013t=summarise(group_by(filter(data,sH==(-74.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
#currentSource2013t$value=currentSource2013t$value*30

#currentSource2013b=summarise(group_by(filter(data,sH<=(-75.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
#currentSource2013b$value=currentSource2013b$value*30

currentSource2003=summarise(group_by(filter(data,sH==(-71.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
currentSource2003$value=currentSource2003$value*8

currentSource2013t=summarise(group_by(filter(data,sH==(-72.5) | sH==(-73.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
currentSource2013t$value=currentSource2013t$value*8

currentSource2013b=summarise(group_by(filter(data,sH==(-74.5) | sH==(-75.5) | sH==(-76.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
currentSource2013b$value=currentSource2013b$value*30

currentSourceBind=bind_rows(currentSource2013b,currentSource2013t,currentSource2003)
#currentSourceBind=currentSource2003
currentSource=summarise(group_by(filter(currentSourceBind),iX,iY,iZ,Emin,Emax),value=sum(value))

transfCof1.25MeV=2.666e-2
transfCof0.8MeV=2.882e-2
transfCof0.5MeV=2.966e-2
transfCof0.3MeV=2.872e-2

data1.25MeV=filter(currentSource,Emin==1.0)
data1.25MeV=mutate(data1.25MeV,kerma=value*transfCof1.25MeV*1.25)
currentSource1.25MeV=summarise(group_by(data1.25MeV,iX,iY,iZ),kerma=sum(kerma))

data0.8MeV=filter(currentSource,Emin==0.6)
data0.8MeV=mutate(data0.8MeV,kerma=value*transfCof0.8MeV*0.8)
currentSource0.8MeV=summarise(group_by(data0.8MeV,iX,iY,iZ),kerma=sum(kerma))

data0.5MeV=filter(currentSource,Emin==0.4)
data0.5MeV=mutate(data0.5MeV,kerma=value*transfCof0.5MeV*0.5)
currentSource0.5MeV=summarise(group_by(data0.5MeV,iX,iY,iZ),kerma=sum(kerma))

data0.3MeV=filter(currentSource,Emin==0.2)
data0.3MeV=mutate(data0.3MeV,kerma=value*transfCof0.3MeV*0.3)
currentSource0.3MeV=summarise(group_by(data0.3MeV,iX,iY,iZ),kerma=sum(kerma))

fullCurrentSource=bind_rows(currentSource1.25MeV,currentSource0.8MeV,currentSource0.5MeV,currentSource0.3MeV)
fullCurrentSource=summarise(group_by(fullCurrentSource,iX,iY,iZ),kerma=sum(kerma))

below1MeVCurrentSource=bind_rows(currentSource0.8MeV,currentSource0.5MeV,currentSource0.3MeV)
below1MeVCurrentSource=summarise(group_by(below1MeVCurrentSource,iX,iY,iZ),kerma=sum(kerma))

normFullCurrentSource=summarise(group_by(filter(fullCurrentSource,iX>=-10 & iX<=10,iY>=(74-10) & iY<=(74+10),iZ==902)),kerma=mean(kerma))
normfac=as.numeric(ssdl[6,4])/as.numeric(normFullCurrentSource)

widthFullCurrentSource=summarise(group_by(filter(fullCurrentSource,iY>=(74-10) & iY<=(74+10)),iX,iZ),kerma=mean(kerma))

heightFullCurrentSource=summarise(group_by(filter(fullCurrentSource,iX>=-10 & iX<=10),iY,iZ),kerma=mean(kerma))

widthBelow1MeVCurrentSource=summarise(group_by(filter(below1MeVCurrentSource,iY>=(74-10) & iY<=(74+10)),iX,iZ),kerma=mean(kerma))

heightBelow1MeVCurrentSource=summarise(group_by(filter(below1MeVCurrentSource,iX>=-10 & iX<=10),iY,iZ),kerma=mean(kerma))

postscript(outGraphWidth902cm,horizontal=FALSE,width=3.125,height=2.25)
g=ggplot()
#g+geom_point(data=filter(widthBelow1MeVCurrentSource,iZ==902),aes(x=iX,y=kerma*normfac),size=0.5,color="wheat")
g+geom_point(data=filter(widthFullCurrentSource,iZ==902),aes(x=iX,y=kerma*normfac),size=0.5,color="burlywood")+geom_errorbar(data=filter(ssdl,h==78,l==902),aes(x=w,ymin=d-d*3.2/100,ymax=d+d*3.2/100),size=1.0,color="darkslategrey",width=20)+xlab("width [cm]")+ylab("air kerma rate [mGy/h]")+labs(caption="20/02/2013 902 cm")+theme_minimal()+theme(plot.caption=element_text(color="slategrey"))+xlim(-300,300)+ylim(0,2)
dev.off()

postscript(outGraphHeight902cm,horizontal=FALSE,width=1.875,height=2.25)
g=ggplot()
#g+geom_point(data=filter(heightBelow1MeVCurrentSource,iZ==902),aes(x=iY,y=kerma*normfac),size=0.5,color="wheat")
g+geom_point(data=filter(heightFullCurrentSource,iZ==902),aes(x=iY,y=kerma*normfac),size=0.5,color="burlywood")+geom_errorbar(data=filter(ssdl,w==0,l==902),aes(x=h,ymin=d-d*3.2/100,ymax=d+d*3.2/100),size=1.0,color="darkslategrey",width=20)+xlab("height [cm]")+ylab("air kerma rate [mGy/h]")+labs(caption="20/02/2013 902 cm")+theme_minimal()+theme(plot.caption=element_text(color="slategrey"))+xlim(0,300)+ylim(0,2)
dev.off()

postscript(outGraphWidth1502cm,horizontal=FALSE,width=3.125,height=2.25)
g=ggplot()
#g+geom_point(data=filter(widthBelow1MeVCurrentSource,iZ==1502),aes(x=iX,y=kerma*normfac),size=0.5,color="wheat")
g+geom_point(data=filter(widthFullCurrentSource,iZ==1502),aes(x=iX,y=kerma*normfac),size=0.5,color="burlywood")+geom_errorbar(data=filter(ssdl,h==78,l==1502),aes(x=w,ymin=d-d*3.2/100,ymax=d+d*3.2/100),size=1.0,color="darkslategrey",width=20)+xlab("width [cm]")+ylab("air kerma rate [mGy/h]")+labs(caption="20/02/2013 1502 cm")+theme_minimal()+theme(plot.caption=element_text(color="slategrey"))+xlim(-300,300)+ylim(0,0.75)
dev.off()

postscript(outGraphHeight1502cm,horizontal=FALSE,width=1.875,height=2.25)
g=ggplot()
#g+geom_point(data=filter(heightBelow1MeVCurrentSource,iZ==1502),aes(x=iY,y=kerma*normfac),size=0.5,color="wheat")
g+geom_point(data=filter(heightFullCurrentSource,iZ==1502),aes(x=iY,y=kerma*normfac),size=0.5,color="burlywood")+geom_errorbar(data=filter(ssdl,w==0,l==1502),aes(x=h,ymin=d-d*3.2/100,ymax=d+d*3.2/100),size=1.0,color="darkslategrey",width=20)+xlab("height [cm]")+ylab("air kerma rate [mGy/h]")+labs(caption="20/02/2013 1502 cm")+theme_minimal()+theme(plot.caption=element_text(color="slategrey"))+xlim(0,300)+ylim(0,0.75)
dev.off()


#g=ggplot(widthData,aes(x=iX,y=value))
#g+facet_wrap(~iZ,ncol=3)+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()

#g=ggplot(heightData,aes(x=iY,y=value))
#g+facet_wrap(~iZ,ncol=3)+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()


```
