---
title: "figaro-analysis"
author: "Elisabeth Lindbo Hansen"
date: "`r date`"
output: html_document
params:
   inFullPath: ""
---

```{r setup, eval=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
```

```{r in, eval=TRUE, include=TRUE}

fullPath=params$inFullPath
#fullPath="/home/elhansen/FIGARO/figaro-results/201700000000"
inFile=str_c(fullPath,".csv")
outGraphWidth902cm=str_c(fullPath,"Width902cm.ps")
outGraphHeight902cm=str_c(fullPath,"Height902m.ps")
data=read_csv(inFile)

ssdl<-read_csv("ssdl_2013.csv")
ssdl$w<-as.double(ssdl$w)
ssdl$h<-as.double(ssdl$h)
ssdl$h=ssdl$h+78
ssdl$l<-as.double(ssdl$l)
ssdl$l=ssdl$l+2
ssdlRef=139.4
ssdlRefUnc=4.5

g=ggplot(data,aes(x=iX,y=iY,fill=value))
g+facet_wrap(~iZ,ncol=3)+geom_raster()+scale_fill_distiller(palette = "RdYlGn",direction=-1)+xlab("width [cm]")+ylab("height [cm]")+coord_fixed(ratio=1)+theme_minimal()

normData=summarise(group_by(filter(data,iX>=-10 & iX<=10,iY>=(74-10) & iY<=(74+10),iZ==902)),value=mean(value))
normfac=as.numeric(ssdl[6,4])/as.numeric(normData)
widthData=summarise(group_by(filter(data,iY>=(74-10) & iY<=(74+10)),iX,iZ),value=mean(value))
heightData=summarise(group_by(filter(data,iX>=-10 & iX<=10),iY,iZ),value=mean(value))

g=ggplot(widthData,aes(x=iX,y=value))
g+facet_wrap(~iZ,ncol=3)+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()

g=ggplot(heightData,aes(x=iY,y=value))
g+facet_wrap(~iZ,ncol=3)+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()

g=ggplot(filter(widthData,iZ==902),aes(x=iX,y=value*normfac))
g+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,h==78,l==902),aes(x=w,y=d,color=c("red"),size=10))
postscript(outGraphWidth902cm)
g+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,h==78,l==902),aes(x=w,y=d,color=c("red"),size=10))
dev.off()

g=ggplot(filter(heightData,iZ==902),aes(x=iY,y=value*normfac))
g+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,w==0,l==902),aes(x=h,y=d,color=c("red"),size=10))
postscript(outGraphHeight902cm)
g+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,w==0,l==902),aes(x=h,y=d,color=c("red"),size=10))
dev.off()

g=ggplot(filter(widthData,iZ==1502),aes(x=iX,y=value*normfac))
g+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,h==78,l==1502),aes(x=w,y=d,color=c("red"),size=10))

g=ggplot(filter(heightData,iZ==1502),aes(x=iY,y=value*normfac))
g+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,w==0,l==1502),aes(x=h,y=d,color=c("red"),size=10))




```
