---
title: "figaro-minisource-analysis"
author: "Elisabeth Lindbo Hansen"
date: "`r date`"
output: html_document
params:
   inFullPath: ""
---

```{r setup, eval=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stringr)
```

```{r in, eval=TRUE, include=TRUE}

fullPath=params$inFullPath
#fullPath="/home/elhansen/FIGARO/figaro-results/201700000000"
inFile=str_c(fullPath,".csv")
outGraphWidth902cm=str_c(fullPath,"Width902cm.ps")
outGraphHeight902cm=str_c(fullPath,"Height902m.ps")
outGraphWidth1502cm=str_c(fullPath,"Width1502cm.ps")
outGraphHeight1502cm=str_c(fullPath,"Height1502m.ps")
data=read_csv(inFile,col_types = "iiinnnnnn")

ssdl<-read_csv("ssdl_2013.csv")
ssdl$w<-as.double(ssdl$w)
ssdl$h<-as.double(ssdl$h)
ssdl$h=ssdl$h+78
ssdl$l<-as.double(ssdl$l)
ssdl$l=ssdl$l+2
ssdlRef=139.4
ssdlRefUnc=4.5

currentSource2003=summarise(group_by(filter(data,sH>=(-73.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
currentSource2003$value=currentSource2003$value*8

currentSource2013t=summarise(group_by(filter(data,sH==(-74.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
currentSource2013t$value=currentSource2013t$value*30

currentSource2013b=summarise(group_by(filter(data,sH<=(-75.5)),iX,iY,iZ,Emin,Emax),value=sum(value))
currentSource2013b$value=currentSource2013b$value*30

currentSourceBind=bind_rows(currentSource2013b,currentSource2013t,currentSource2003)
#currentSourceBind=currentSource2003
currentSource=summarise(group_by(filter(currentSourceBind),iX,iY,iZ,Emin,Emax),value=sum(value))

transfCof1.25MeV=2.666e-2
transfCof0.8MeV=2.882e-2
transfCof0.5MeV=2.966e-2
transfCof0.3MeV=2.872e-2

data1.25MeV=filter(currentSource,Emin==1.0)
data1.25MeV=mutate(data1.25MeV,kerma=value*transfCof1.25MeV)

data0.8MeV=filter(currentSource,Emin==0.6)
data0.8MeV=mutate(data0.8MeV,kerma=value*transfCof0.8MeV)

data0.5MeV=filter(currentSource,Emin==0.4)
data0.5MeV=mutate(data0.5MeV,kerma=value*transfCof0.5MeV)

data0.3MeV=filter(currentSource,Emin==0.2)
data0.3MeV=mutate(data0.3MeV,kerma=value*transfCof0.3MeV)

currentSource=bind_rows(data1.25MeV,data0.8MeV,data0.5MeV,data0.3MeV)

normCurrentSource=summarise(group_by(filter(currentSource,iX>=-10 & iX<=10,iY>=(74-10) & iY<=(74+10),iZ==902)),kerma=mean(kerma))
normfac=as.numeric(ssdl[6,4])/as.numeric(normCurrentSource)

widthCurrentSource=summarise(group_by(filter(currentSource,iY>=(74-10) & iY<=(74+10)),iX,iZ),kerma=mean(kerma))

heightCurrentSource=summarise(group_by(filter(currentSource,iX>=-10 & iX<=10),iY,iZ),kerma=mean(kerma))

gW902=ggplot(filter(widthCurrentSource,iZ==902),aes(x=iX,y=kerma*normfac))

gH902=ggplot(filter(heightCurrentSource,iZ==902),aes(x=iY,y=kerma*normfac))

gW902+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,h==78,l==902),aes(x=w,y=d,color=c("red"),size=10))

gH902+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,w==0,l==902),aes(x=h,y=d,color=c("red"),size=10))

gW1502=ggplot(filter(widthCurrentSource,iZ==1502),aes(x=iX,y=kerma*normfac))

gH1502=ggplot(filter(heightCurrentSource,iZ==1502),aes(x=iY,y=kerma*normfac))

gW1502+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,h==78,l==1502),aes(x=w,y=d,color=c("red"),size=10))

gH1502+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,w==0,l==1502),aes(x=h,y=d,color=c("red"),size=10))


postscript(outGraphWidth902cm)
gW902+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,h==78,l==902),aes(x=w,y=d,color=c("red"),size=10))
dev.off()

postscript(outGraphHeight902cm)
gH902+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,w==0,l==902),aes(x=h,y=d,color=c("red"),size=10))
dev.off()

postscript(outGraphWidth1502cm)
gW1502+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,h==78,l==1502),aes(x=w,y=d,color=c("red"),size=10))
dev.off()

postscript(outGraphHeight1502cm)
gH1502+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()+geom_point(data=filter(ssdl,w==0,l==1502),aes(x=h,y=d,color=c("red"),size=10))
dev.off()


g=ggplot(widthData,aes(x=iX,y=value))
g+facet_wrap(~iZ,ncol=3)+geom_point()+xlab("width [cm]")+ylab("")+theme_minimal()

g=ggplot(heightData,aes(x=iY,y=value))
g+facet_wrap(~iZ,ncol=3)+geom_point()+xlab("height [cm]")+ylab("")+theme_minimal()


```
